"""Conservative single-camera shuttle landing review for the local Web UI.

This is intentionally *not* an official Hawk-Eye system.  An official line
call needs synchronised, calibrated high-speed cameras and a 3-D flight
reconstruction.  The local pipeline has one camera, a 2-D court homography,
and a measured shuttle track.  We therefore review only the terminal flight
of a rally and publish a result when a measured motion-to-rest landing event
is present.  A last-seen/airborne endpoint is not a landing and produces no
coordinate or line distance.  Anything close to a line is deliberately left
as ``review``.

The module is separated from the renderer so the conservative evidence rules
can be unit-tested from a CSV-shaped list of rows.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path
from statistics import median
from typing import Any, Iterable, Mapping, Sequence


COURT_WIDTH_M = 6.10
COURT_LENGTH_M = 13.40
LINE_AMBIGUITY_M = 0.20
# A confirmed landing uses the wider sanity envelope below.  Endpoint proxies
# from older manifests are filtered at the public API boundary and are never
# regenerated by the current report builder.
_MAX_ENDPOINT_OUTSIDE_M = 3.0
# Even a confirmed single-camera landing becomes poorly conditioned when it is
# far beyond the calibrated rectangle.  Keep a separate, tighter publication
# limit so a valid-looking body lock cannot turn into a metre-scale margin.
_MAX_CONFIRMED_LANDING_OUTSIDE_M = 1.0
_REAL_SOURCES = {"model", "classical"}
# Edge detections are useful for reconstructing the flight context, but they
# are not stable enough to be projected as a ground point.  Keeping this set
# separate prevents a last pixel at the top of the image from becoming a
# several-metre line distance.
_FLIGHT_SOURCES = _REAL_SOURCES | {"model_edge"}
_MAX_CANDIDATES = 80
# A terminal point is not a landing merely because it is the last point in a
# CSV.  The open-source TrackNet/BounceNet family first looks for a motion to
# rest transition (and rejects a later "resurrection"); keep the same event
# boundary here.  The pixel thresholds below are scaled from the calibrated
# court quadrilateral, so a 720p and a 1080p export use comparable evidence.
_LANDING_MIN_OBSERVATIONS = 5
_LANDING_MIN_SPAN_SECONDS = 0.16
_LANDING_MIN_APPROACH_RATIO = 0.012
_LANDING_MIN_MOTION_RATIO = 0.012
_LANDING_SETTLE_RATIO = 0.012
_LANDING_MAX_APPROACH_RATIO = 0.050
_LANDING_MAX_SPEED_TURN_COSINE = 0.25
_LANDING_MAX_SPEED_RATIO = 3.5
_LANDING_RESURRECTION_RATIO = 0.020
# A detector can remain on a white shoe, racket, or shirt after the shuttle
# has disappeared.  A static branch is only allowed to veto a preceding shot
# when it also has two-sided, sufficiently fast ball evidence.  These values
# are deliberately expressed in court-scale pixels where possible.
_CONTACT_MIN_SPEED_RATIO = 0.008
_CONTACT_MIN_POST_DISPLACEMENT_RATIO = 0.018
_CONTACT_MAX_EVENT_GAP_FRAMES = 2
_TERMINAL_REST_MIN_FRAMES = 3
_TERMINAL_REST_MAX_SPREAD_RATIO = 0.014
_TERMINAL_VIDEO_MIN_VISIBLE_FRAMES = 8
_TERMINAL_VIDEO_MAX_CENTROID_STD_PX = 3.5
_TERMINAL_VIDEO_DIFF_THRESHOLD = 12.0
_TERMINAL_VIDEO_MIN_VALUE = 145.0
_TERMINAL_VIDEO_MAX_SATURATION = 145.0
_TERMINAL_VIDEO_MAX_COMPONENT_AREA = 180
_TERMINAL_VIDEO_MIN_COMPONENT_AREA = 8
# A single temporal median is easily contaminated when a player covers the
# search area during the reference window.  Keep a few independent medians so
# a residual has to be new relative to the same background in most windows.
_TERMINAL_VIDEO_REFERENCE_COUNT = 3
_TERMINAL_VIDEO_MIN_REFERENCE_FRAMES = 6
_TERMINAL_VIDEO_REFERENCE_AGREEMENT = 0.67
# Court paint and net tape are long, thin bright structures.  A shuttle-sized
# component should be compact; this gate is intentionally permissive enough
# for a perspective-stretched shuttle but rejects line fragments.
_TERMINAL_VIDEO_MAX_ASPECT_RATIO = 4.5
_TERMINAL_VIDEO_LINE_BAND_PX = 5.0
_TERMINAL_VIDEO_MAX_FRAME_GAP = 2
_TERMINAL_VIDEO_SEARCH_RADIUS_RATIO = 0.13
_TERMINAL_VIDEO_MAX_RANGE_SECONDS = 1.8
_TERMINAL_VIDEO_PRE_GAP_FRAMES = 45
_TERMINAL_VIDEO_PRE_WINDOW_FRAMES = 24
_TERMINAL_VIDEO_POST_OFFSET_FRAMES = 4
_TERMINAL_VIDEO_POST_WINDOW_FRAMES = 60
# A local sequence-consistency repair is useful context for a coach, but it
# cannot decide the striker for a line-call.  Keep this explicit rather than
# relying on a numeric confidence threshold that future exports may change.
_REVIEW_ONLY_HITTER_SOURCES = {
    "rally_alternation_inferred",
    "rally_alternation_corrected",
}
_REJECTION_CODES = (
    "no_rallies",
    "no_confirmed_hit",
    "no_post_hit_observation",
    "shot_continues_to_next_contact",
    "later_hit_unconfirmed",
    "discontinuous_terminal_track",
    "flight_too_short",
    "no_landing_evidence",
    "projection_failed",
    "landing_out_of_bounds",
    "wrong_target_half",
    "low_confidence",
    "invalid_calibration",
    "source_unavailable",
    "read_failed",
)
_REJECTION_NOTICES = {
    "no_rallies": "没有可复核的有效回合",
    "no_confirmed_hit": "没有确认击球事件",
    "no_post_hit_observation": "最后击球后没有真实球点",
    "shot_continues_to_next_contact": "后续已检测到接触，请回看视频",
    "later_hit_unconfirmed": "后续有未确认击球，请回看视频",
    "discontinuous_terminal_track": "终局轨迹不连续",
    "flight_too_short": "终局轨迹持续时间不足",
    "no_landing_evidence": "未观察到可靠落地事件，请回看视频",
    "projection_failed": "终局轨迹无法映射到球场",
    "landing_out_of_bounds": "终点超出可信球场范围",
    "wrong_target_half": "终点不在击球方的目标半场",
    "low_confidence": "终局轨迹证据质量不足",
}


def _number(value: object, default: float | None = None) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if math.isfinite(number) else default


def _integer(value: object, default: int = 0) -> int:
    number = _number(value)
    return int(number) if number is not None else int(default)


def _timecode(frame: int, fps: float) -> str:
    seconds = max(0.0, float(frame) / max(float(fps), 1.0))
    minutes, remainder = divmod(int(seconds), 60)
    return f"{minutes:02d}:{remainder:02d}"


def _empty_report(
    status: str,
    notice: str,
    *,
    reason_code: str | None = None,
) -> dict[str, Any]:
    report = {
        "version": 1,
        "status": status,
        "notice": notice,
        "court": {
            "width_m": COURT_WIDTH_M,
            "length_m": COURT_LENGTH_M,
            "line_margin_cm": int(round(LINE_AMBIGUITY_M * 100)),
        },
        "summary": {
            "reviewed_rallies": 0,
            "candidate_count": 0,
            "in_count": 0,
            "out_count": 0,
            "review_count": 0,
        },
        "candidates": [],
    }
    if reason_code in _REJECTION_CODES:
        report["diagnostics"] = {
            "reason_counts": [{"code": reason_code, "count": 1}],
        }
    return report


def _is_confirmed_hit(row: Mapping[str, object]) -> bool:
    """Apply the same confirmed-event contract used by BST and coaching.

    ``HitUncertain`` and ``HitBallObserved`` were added after the lightweight
    index CSV format.  Missing values therefore retain legacy compatibility,
    while explicit negative evidence can never become the terminal anchor.
    """
    if _integer(row.get("Hit"), 0) <= 0 or _integer(row.get("Frame"), -1) < 0:
        return False
    if _integer(row.get("HitUncertain"), 0) > 0:
        return False
    ball_observed = _number(row.get("HitBallObserved"))
    return ball_observed is None or ball_observed > 0.0


def _is_strong_unconfirmed_hit(row: Mapping[str, object]) -> bool:
    """Recognise a likely later contact without promoting it to a hard hit.

    The tracking sidecar can deliberately mark a contact ``HitUncertain``.
    Most such rows are harmless noise and must stay ignored.  A row carrying
    both a visible ball and high-confidence pose-contact evidence is different:
    it says the rally continued after the last hard hit, so the preceding
    terminal run cannot be a confirmed landing.  This mirrors the event
    classifiers' ``hit``/``none`` separation while keeping the hard-hit
    contract conservative.
    """
    if _integer(row.get("Hit"), 0) <= 0 or _is_confirmed_hit(row):
        return False
    if _number(row.get("HitBallObserved"), 0.0) <= 0.0:
        return False
    score = _number(row.get("HitScore"), 0.0) or 0.0
    hitter_confidence = _number(row.get("HitHitterConfidence"), 0.0) or 0.0
    hitter_source = str(row.get("HitHitterSource", "")).strip().lower()
    if (
        hitter_source == "pose_contact"
        and hitter_confidence >= 0.85
        and score >= 0.70
    ):
        return True
    # Some older exports do not persist the hitter-source field.  Require a
    # materially stronger score in that format rather than treating every
    # uncertain curvature response as a rally continuation.
    hit_source = str(row.get("HitSource", "")).strip().lower()
    return (
        hit_source in {"curvature", "edge_exit"}
        and score >= 0.88
    ) or (score >= 0.90 and hitter_confidence >= 0.90)


def _uncertain_hit_has_two_sided_flight(
    row: Mapping[str, object],
    ordered_rows: Sequence[Mapping[str, object]],
    *,
    court_scale_px: float,
) -> bool:
    """Check whether a HIT? row really looks like a new racket contact.

    ``ShotEndFrame`` is populated by the overlay for the next *counted*
    event, and counted events may be uncertain.  A player/balloon lock often
    has a pose-contact score but no outgoing flight.  Require real points on
    both sides of the event, a fast enough outgoing segment, and a meaningful
    turn or speed change before allowing such a row to terminate the shot.
    """
    if not _is_strong_unconfirmed_hit(row):
        return False
    event_frame = _integer(row.get("Frame"), -1)
    event_observation = _observation(row)
    if event_frame < 0 or event_observation is None:
        return False
    observations = [
        item
        for raw in ordered_rows
        if abs(_integer(raw.get("Frame"), -1) - event_frame)
        <= max(6, _CONTACT_MAX_EVENT_GAP_FRAMES * 3)
        for item in [_observation(raw)]
        if item is not None
    ]
    observations.sort(key=lambda item: int(item["frame"]))
    before = [item for item in observations if int(item["frame"]) < event_frame]
    after = [item for item in observations if int(item["frame"]) > event_frame]
    if len(before) < 2 or len(after) < 3:
        return False
    before = before[-3:]
    after = after[:4]
    if any(
        int(second["frame"]) - int(first["frame"]) > _CONTACT_MAX_EVENT_GAP_FRAMES
        for first, second in zip(before, before[1:])
    ) or int(event_frame) - int(before[-1]["frame"]) > _CONTACT_MAX_EVENT_GAP_FRAMES:
        return False
    if any(
        int(second["frame"]) - int(first["frame"]) > _CONTACT_MAX_EVENT_GAP_FRAMES
        for first, second in zip(after, after[1:])
    ) or int(after[0]["frame"]) - int(event_frame) > _CONTACT_MAX_EVENT_GAP_FRAMES:
        return False

    def _speed(first: Mapping[str, Any], second: Mapping[str, Any]) -> float:
        gap = max(1, int(second["frame"]) - int(first["frame"]))
        return math.hypot(
            float(second["x"]) - float(first["x"]),
            float(second["y"]) - float(first["y"]),
        ) / gap

    pre_speeds = [_speed(first, second) for first, second in zip(before, before[1:])]
    pre_speeds.append(_speed(before[-1], event_observation))
    post_speeds = [_speed(event_observation, after[0])]
    post_speeds.extend(_speed(first, second) for first, second in zip(after, after[1:]))
    min_speed = max(
        4.0,
        _CONTACT_MIN_SPEED_RATIO * max(float(court_scale_px), 400.0),
    )
    pre_speed = float(median(pre_speeds[-2:]))
    post_speed = float(median(post_speeds[:3]))
    if pre_speed < min_speed or post_speed < min_speed:
        return False
    post_displacement = math.hypot(
        float(after[min(2, len(after) - 1)]["x"]) - float(event_observation["x"]),
        float(after[min(2, len(after) - 1)]["y"]) - float(event_observation["y"]),
    )
    if post_displacement < max(
        8.0,
        _CONTACT_MIN_POST_DISPLACEMENT_RATIO * max(float(court_scale_px), 400.0),
    ):
        return False
    pre_vector = (
        float(event_observation["x"]) - float(before[-1]["x"]),
        float(event_observation["y"]) - float(before[-1]["y"]),
    )
    post_vector = (
        float(after[0]["x"]) - float(event_observation["x"]),
        float(after[0]["y"]) - float(event_observation["y"]),
    )
    pre_norm = math.hypot(*pre_vector)
    post_norm = math.hypot(*post_vector)
    if pre_norm <= 1e-6 or post_norm <= 1e-6:
        return False
    cosine = (
        pre_vector[0] * post_vector[0]
        + pre_vector[1] * post_vector[1]
    ) / (pre_norm * post_norm)
    speed_ratio = post_speed / max(pre_speed, 1e-6)
    return cosine <= 0.65 or speed_ratio >= 1.35 or speed_ratio <= 0.55


def _court_homography(court_points: Sequence[object]):
    """Build the image-to-court transform, rejecting weak calibration input."""
    try:
        import cv2
        import numpy as np

        values = [float(value) for value in court_points]
        if len(values) != 8 or not all(math.isfinite(value) for value in values):
            return None
        source = np.asarray(values, dtype=np.float32).reshape(4, 2)
        if abs(float(cv2.contourArea(source))) < 64.0:
            return None
        destination = np.asarray(
            [
                [0.0, 0.0],
                [COURT_WIDTH_M, 0.0],
                [COURT_WIDTH_M, COURT_LENGTH_M],
                [0.0, COURT_LENGTH_M],
            ],
            dtype=np.float32,
        )
        matrix = cv2.getPerspectiveTransform(source, destination)
        if matrix.shape != (3, 3) or not np.isfinite(matrix).all():
            return None
        determinant = float(np.linalg.det(matrix))
        return matrix if math.isfinite(determinant) and abs(determinant) > 1e-12 else None
    except Exception:
        return None


def _court_pixel_scale(court_points: Sequence[object]) -> float:
    """Return a stable pixel scale derived from the calibrated court area.

    ``sqrt(area)`` is deliberately used instead of a video-wide width/height:
    the latter is not available in lightweight sidecars and would make the
    event gate dependent on a crop.  A conservative fallback keeps synthetic
    or legacy reports usable when the calibration is malformed; the
    homography itself still remains the hard calibration gate.
    """
    try:
        values = [float(value) for value in court_points]
        if len(values) != 8 or not all(math.isfinite(value) for value in values):
            return 800.0
        points = list(zip(values[::2], values[1::2]))
        area_twice = sum(
            points[index][0] * points[(index + 1) % 4][1]
            - points[(index + 1) % 4][0] * points[index][1]
            for index in range(4)
        )
        area = abs(float(area_twice)) * 0.5
        if not math.isfinite(area) or area <= 64.0:
            return 800.0
        return max(400.0, min(1800.0, math.sqrt(area)))
    except Exception:
        return 800.0


def _project(matrix, x: float, y: float) -> tuple[float, float] | None:
    try:
        import cv2
        import numpy as np

        source = np.asarray([[[float(x), float(y)]]], dtype=np.float32)
        projected = cv2.perspectiveTransform(source, matrix)[0][0]
        result = (float(projected[0]), float(projected[1]))
        return result if all(math.isfinite(value) for value in result) else None
    except Exception:
        return None


def _observation(
    row: Mapping[str, object],
    *,
    allowed_sources: set[str] | frozenset[str] | None = None,
) -> dict[str, Any] | None:
    """Return only an actual detector observation, never an interpolated track.

    New sidecars expose Raw* fields.  The fallback supports the lighter index
    CSV and intentionally still accepts only the model/classical sources.
    """
    frame = _integer(row.get("Frame"), -1)
    if frame < 0:
        return None
    raw_visibility = _number(row.get("RawVisibility"))
    if raw_visibility is not None:
        visible = raw_visibility > 0.0
        x, y = _number(row.get("RawX")), _number(row.get("RawY"))
        source = str(row.get("RawSource", "")).strip().lower()
        confidence = _number(row.get("RawConfidence"))
    else:
        visible = _integer(row.get("Visibility"), 0) > 0
        x, y = _number(row.get("X")), _number(row.get("Y"))
        source = str(row.get("Source", "")).strip().lower()
        confidence = _number(row.get("Confidence"))
    sources = _REAL_SOURCES if allowed_sources is None else allowed_sources
    if not visible or source not in sources or x is None or y is None:
        return None
    if confidence is None:
        # Older sidecars did not persist detector confidence.  Treat that as
        # useful but not perfect evidence, rather than fabricating certainty.
        confidence = 0.65
    return {
        "frame": frame,
        "x": float(x),
        "y": float(y),
        "confidence": max(0.0, min(1.0, float(confidence))),
        "source": source,
    }


def _observation_runs(
    observations: Sequence[dict[str, Any]], max_gap_frames: int
) -> list[list[dict[str, Any]]]:
    """Split detector observations instead of bridging an invisible interval."""
    if not observations:
        return []
    ordered = sorted(observations, key=lambda item: int(item["frame"]))
    runs = [[ordered[0]]]
    for item in ordered[1:]:
        if int(item["frame"]) - int(runs[-1][-1]["frame"]) <= max_gap_frames:
            runs[-1].append(item)
        else:
            runs.append([item])
    return runs


def _signed_line_distance(x_m: float, y_m: float) -> float:
    """Positive inside, negative outside; magnitude is distance to the boundary."""
    inside = (
        0.0 <= x_m <= COURT_WIDTH_M
        and 0.0 <= y_m <= COURT_LENGTH_M
    )
    if inside:
        return min(x_m, COURT_WIDTH_M - x_m, y_m, COURT_LENGTH_M - y_m)
    dx = max(0.0, -x_m, x_m - COURT_WIDTH_M)
    dy = max(0.0, -y_m, y_m - COURT_LENGTH_M)
    return -math.hypot(dx, dy)


def _decision(signed_distance_m: float) -> str:
    if abs(float(signed_distance_m)) <= LINE_AMBIGUITY_M:
        return "review"
    return "in" if signed_distance_m > 0.0 else "out"


def _expected_target_ok(hitter: str, y_m: float) -> bool | None:
    """Check only the broad opponent half, with a net-zone tolerance.

    This stops a lost track or a net-side collapse from being shown as a normal
    line-call candidate.  Unknown hitter attribution is allowed at lower
    confidence because it is still possible to inspect the trajectory.
    """
    mid = COURT_LENGTH_M * 0.5
    tolerance = 0.55
    if hitter == "near":
        return y_m <= mid + tolerance
    if hitter == "far":
        return y_m >= mid - tolerance
    return None


def _landing_event_evidence(
    tail: Sequence[dict[str, Any]],
    *,
    fps: float,
    court_scale_px: float = 800.0,
) -> dict[str, Any] | None:
    """Return evidence for a measured landing/rest transition.

    This is the small rule layer shared by the open-source badminton event
    detectors: high motion must be followed by a sustained low-motion tail,
    with no implausible jump into the stationary points.  It is intentionally
    stricter than a terminal-endpoint heuristic.  A caller must not project a
    point onto the court when this returns ``None``.
    """
    if len(tail) < _LANDING_MIN_OBSERVATIONS:
        return None
    ordered = sorted(tail, key=lambda item: int(item["frame"]))
    frames = [int(item["frame"]) for item in ordered]
    gaps = [frames[index + 1] - frames[index] for index in range(len(frames) - 1)]
    if any(gap <= 0 or gap > 2 for gap in gaps):
        return None
    # A single missing frame may be tolerated in the approach, but the three
    # observations used to declare rest must be truly consecutive.
    if any(gap != 1 for gap in gaps[-2:]):
        return None
    min_span = max(
        4,
        int(round(max(float(fps), 1.0) * _LANDING_MIN_SPAN_SECONDS)),
    )
    if frames[-1] - frames[0] < min_span:
        return None

    scale = max(400.0, min(1800.0, float(court_scale_px or 800.0)))
    settle_limit = max(4.0, min(12.0, _LANDING_SETTLE_RATIO * scale))
    motion_limit = max(8.0, min(18.0, _LANDING_MIN_MOTION_RATIO * scale))
    approach_min = max(7.0, _LANDING_MIN_APPROACH_RATIO * scale)
    approach_max = max(28.0, _LANDING_MAX_APPROACH_RATIO * scale)
    resurrection_limit = max(14.0, _LANDING_RESURRECTION_RATIO * scale)

    last = ordered[-3:]
    pair_distances = [
        math.hypot(
            float(first["x"]) - float(second["x"]),
            float(first["y"]) - float(second["y"]),
        )
        for index, first in enumerate(last)
        for second in last[index + 1:]
    ]
    if not pair_distances or max(pair_distances) > settle_limit:
        return None

    confidences = [float(item.get("confidence", 0.0)) for item in last]
    if min(confidences) < 0.35 or sum(confidences) / len(confidences) < 0.55:
        return None

    # ``transition_index`` is the first of the three settled observations.
    # The two intervals before it establish approach motion; the two after it
    # must remain slow.  Frame gaps are normalised so a single flicker frame
    # cannot look like a false speed drop.
    transition_index = len(ordered) - 3
    speeds: list[float] = []
    vectors: list[tuple[float, float]] = []
    for first, second, gap in zip(ordered, ordered[1:], gaps):
        dx = float(second["x"]) - float(first["x"])
        dy = float(second["y"]) - float(first["y"])
        vectors.append((dx, dy))
        speeds.append(math.hypot(dx, dy) / max(1, gap))
    approach_speed = speeds[transition_index - 1]
    previous_speed = speeds[transition_index - 2]
    if approach_speed < approach_min or previous_speed < approach_min * 0.55:
        return None

    # A stationary body/advertising-board lock often begins with one large
    # coordinate jump.  A real shuttle decelerating onto the floor should not
    # make a one-frame jump many times larger than its preceding flight step.
    if approach_speed > max(approach_max, previous_speed * _LANDING_MAX_SPEED_RATIO):
        return None

    previous_vector = vectors[transition_index - 2]
    approach_vector = vectors[transition_index - 1]
    previous_norm = math.hypot(*previous_vector)
    approach_norm = math.hypot(*approach_vector)
    if previous_norm > 1e-6 and approach_norm > 1e-6:
        cosine = (
            previous_vector[0] * approach_vector[0]
            + previous_vector[1] * approach_vector[1]
        ) / (previous_norm * approach_norm)
        if cosine < _LANDING_MAX_SPEED_TURN_COSINE:
            return None
    else:
        return None

    rest_x = float(median(float(item["x"]) for item in last))
    rest_y = float(median(float(item["y"]) for item in last))
    motion_to_rest = math.hypot(
        float(ordered[transition_index - 1]["x"]) - rest_x,
        float(ordered[transition_index - 1]["y"]) - rest_y,
    )
    if motion_to_rest < motion_limit:
        return None

    post_speeds = speeds[transition_index:]
    if not post_speeds or max(post_speeds) > settle_limit:
        return None
    # Future-activity check from BounceNet: a candidate that immediately
    # resumes high-speed motion is a turn/occlusion, not a landing.
    if any(speed > resurrection_limit for speed in post_speeds):
        return None

    return {
        "event_frame": int(last[0]["frame"]),
        "x": rest_x,
        "y": rest_y,
        "approach_speed": round(approach_speed, 3),
        "settle_speed": round(max(post_speeds), 3),
        "settle_spread": round(max(pair_distances), 3),
    }


def _stable_terminal_windows(
    run: Sequence[dict[str, Any]],
    *,
    court_scale_px: float,
) -> list[dict[str, Any]]:
    """Find short, consecutive, low-motion windows in a detector run.

    These windows are only *search hints* for the video fallback.  They are
    not accepted as a landing by themselves: the original video must contain
    a new persistent shuttle-shaped object at the same place.
    """
    ordered = sorted(run, key=lambda item: int(item["frame"]))
    if len(ordered) < _TERMINAL_REST_MIN_FRAMES:
        return []
    spread_limit = max(
        4.0,
        min(14.0, _TERMINAL_REST_MAX_SPREAD_RATIO * max(float(court_scale_px), 400.0)),
    )
    windows: list[dict[str, Any]] = []
    for index in range(0, len(ordered) - 2):
        window = ordered[index:index + 3]
        frames = [int(item["frame"]) for item in window]
        if frames[1] - frames[0] != 1 or frames[2] - frames[1] != 1:
            continue
        pair_distances = [
            math.hypot(
                float(first["x"]) - float(second["x"]),
                float(first["y"]) - float(second["y"]),
            )
            for left, first in enumerate(window)
            for second in window[left + 1:]
        ]
        if not pair_distances or max(pair_distances) > spread_limit:
            continue
        confidences = [float(item.get("confidence", 0.0)) for item in window]
        if min(confidences) < 0.35 or sum(confidences) / len(confidences) < 0.55:
            continue
        windows.append({
            "frame": frames[0],
            "end_frame": frames[-1],
            "x": float(median(float(item["x"]) for item in window)),
            "y": float(median(float(item["y"]) for item in window)),
            "spread": max(pair_distances),
            "confidence": sum(confidences) / len(confidences),
        })
    return windows


def _boundary_from_point(
    point: tuple[float, float],
    *,
    width_m: float = COURT_WIDTH_M,
    length_m: float = COURT_LENGTH_M,
    margin_m: float = 0.05,
) -> tuple[str, float] | None:
    """Return one unambiguous court boundary and its outside distance."""
    x_m, y_m = float(point[0]), float(point[1])
    distances = {
        "left_sideline": -x_m,
        "right_sideline": x_m - width_m,
        "far_baseline": -y_m,
        "near_baseline": y_m - length_m,
    }
    outside = [(name, value) for name, value in distances.items() if value > margin_m]
    if len(outside) != 1:
        return None
    return outside[0]


def _boundary_image_point(
    boundary: str,
    x: float,
    *,
    court_points: Sequence[object],
) -> tuple[float, float] | None:
    """Interpolate a point on the selected image-space court edge."""
    try:
        values = [float(value) for value in court_points]
        if len(values) != 8 or not all(math.isfinite(value) for value in values):
            return None
        points = [
            (values[index], values[index + 1])
            for index in range(0, 8, 2)
        ]
        if boundary == "far_baseline":
            left, right = points[0], points[1]
        elif boundary == "near_baseline":
            left, right = points[3], points[2]
        elif boundary == "left_sideline":
            left, right = points[0], points[3]
        elif boundary == "right_sideline":
            left, right = points[1], points[2]
        else:
            return None
        # For a baseline x is the horizontal image coordinate.  For a side
        # line, callers pass the image y coordinate in ``x``.
        if boundary in {"far_baseline", "near_baseline"}:
            denominator = right[0] - left[0]
            if abs(denominator) < 1e-6:
                return None
            ratio = (float(x) - left[0]) / denominator
        else:
            denominator = right[1] - left[1]
            if abs(denominator) < 1e-6:
                return None
            ratio = (float(x) - left[1]) / denominator
        ratio = max(-0.25, min(1.25, ratio))
        return (
            float(left[0] + ratio * (right[0] - left[0])),
            float(left[1] + ratio * (right[1] - left[1])),
        )
    except Exception:
        return None


def _video_frame_crops(
    video_path: Path | str,
    frame_numbers: Sequence[int],
    *,
    x0: int,
    y0: int,
    x1: int,
    y1: int,
) -> dict[int, Any]:
    """Read a small set of crops without loading the full source video."""
    try:
        import cv2
        import numpy as np

        wanted = sorted({int(frame) for frame in frame_numbers if int(frame) >= 0})
        if not wanted:
            return {}
        capture = cv2.VideoCapture(str(video_path))
        if not capture.isOpened():
            return {}
        result: dict[int, Any] = {}
        capture.set(cv2.CAP_PROP_POS_FRAMES, wanted[0])
        wanted_set = set(wanted)
        current = wanted[0]
        end = wanted[-1]
        while current <= end:
            ok, frame = capture.read()
            if not ok:
                break
            if current in wanted_set:
                height, width = frame.shape[:2]
                xa = max(0, min(width, int(x0)))
                xb = max(xa, min(width, int(x1)))
                ya = max(0, min(height, int(y0)))
                yb = max(ya, min(height, int(y1)))
                if xb > xa and yb > ya:
                    result[current] = frame[ya:yb, xa:xb].copy()
            current += 1
        capture.release()
        return result
    except Exception:
        return {}


def _recover_terminal_rest_from_video(
    video_path: Path | str | None,
    rows: Sequence[Mapping[str, object]],
    *,
    hit_frame: int,
    context_end_frame: int,
    fps: float,
    matrix,
    court_points: Sequence[object],
    court_scale_px: float,
) -> dict[str, Any] | None:
    """Recover a shuttle that becomes visible after a player occlusion.

    TrackNet deliberately marks a freshly settled shuttle as missing in many
    clips (it has no motion cue).  A fixed-camera median/difference check can
    recover a *new, small, white, persistent* object near the extrapolated
    terminal area.  It is only used after a rally's measured flight; static
    court lines disappear in the pre/post difference and moving shoes fail
    the persistence/centroid gate.
    """
    if not video_path:
        return None
    path = Path(video_path)
    if not path.is_file():
        return None
    try:
        import cv2
        import numpy as np
    except Exception:
        return None

    ordered_rows = sorted(rows, key=lambda row: _integer(row.get("Frame"), -1))
    strict_observations = [
        item
        for row in ordered_rows
        if hit_frame < _integer(row.get("Frame"), -1) <= max(context_end_frame, hit_frame)
        for item in [_observation(row)]
        if item is not None
    ]
    if not strict_observations:
        return None
    runs = _observation_runs(strict_observations, max_gap_frames=2)
    windows: list[dict[str, Any]] = []
    for run in runs:
        windows.extend(_stable_terminal_windows(run, court_scale_px=court_scale_px))
    if not windows:
        return None

    # Prefer the latest stable branch that is close to a court edge.  A later
    # player/board lock often has no three-frame stable window before the
    # soft ShotEndFrame cutoff; if it does, the geometric range gate below
    # rejects it as far outside the plausible landing band.
    selected = None
    selected_boundary = None
    selected_projection = None
    for window in sorted(windows, key=lambda item: int(item["frame"]), reverse=True):
        projected = _project(matrix, float(window["x"]), float(window["y"]))
        if projected is None:
            continue
        boundary = _boundary_from_point(projected, margin_m=0.05)
        if boundary is None:
            # An inside stable point can still be a landing; use its nearest
            # edge as the search anchor, but rank an outside point first.
            distances = {
                "left_sideline": abs(float(projected[0])),
                "right_sideline": abs(float(projected[0]) - COURT_WIDTH_M),
                "far_baseline": abs(float(projected[1])),
                "near_baseline": abs(float(projected[1]) - COURT_LENGTH_M),
            }
            boundary = (min(distances, key=distances.get), 0.0)
        # The 905–907 body/leg branch in the reference clip maps far beyond
        # any plausible ground band.  Keep it as an image search hint, but do
        # not let it become a candidate without a newly visible object.
        if boundary[1] > 3.0:
            continue
        selected = window
        selected_boundary = boundary[0]
        selected_projection = projected
        break
    if selected is None or selected_boundary is None or selected_projection is None:
        return None

    boundary_pixel = _boundary_image_point(
        selected_boundary,
        float(selected["x"])
        if selected_boundary in {"far_baseline", "near_baseline"}
        else float(selected["y"]),
        court_points=court_points,
    )
    if boundary_pixel is None:
        return None
    radius = int(max(
        54.0,
        min(125.0, _TERMINAL_VIDEO_SEARCH_RADIUS_RATIO * max(court_scale_px, 400.0)),
    ))
    # Search around the actual court edge, not around an airborne/body proxy.
    # This is what separates the y≈445 sock lock from the y≈469 settled ball.
    center_x = int(round(boundary_pixel[0]))
    center_y = int(round(boundary_pixel[1]))
    x0, x1 = center_x - radius, center_x + radius
    y0, y1 = center_y - radius, center_y + radius
    rest_start = int(selected["frame"])
    # Keep the reference strictly before the candidate rest window.  For a
    # short synthetic/low-FPS flight, ``hit + 8`` can otherwise land after
    # ``rest_start`` and contaminate the background with the shuttle itself.
    pre_end = min(
        rest_start - 1,
        max(hit_frame + 8, rest_start - _TERMINAL_VIDEO_PRE_GAP_FRAMES),
    )
    pre_start = max(hit_frame + 1, pre_end - _TERMINAL_VIDEO_PRE_WINDOW_FRAMES)
    post_start = max(rest_start + _TERMINAL_VIDEO_POST_OFFSET_FRAMES, pre_end + 1)
    post_end = post_start + min(
        int(round(max(float(fps), 1.0) * _TERMINAL_VIDEO_MAX_RANGE_SECONDS)),
        _TERMINAL_VIDEO_POST_WINDOW_FRAMES,
    )
    # Prefer several short windows before the confirmed hit.  The local
    # ``pre_start..pre_end`` interval can collapse to only a handful of frames
    # when the detector's terminal hint is close to the hit (as in the
    # reference clip), which defeats the multi-background safeguard.  A small
    # guard before the hit avoids including the racket-contact flash while
    # still giving the median enough clean court views.
    reference_group_size = max(
        _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES,
        int(math.ceil(
            _TERMINAL_VIDEO_PRE_WINDOW_FRAMES / _TERMINAL_VIDEO_REFERENCE_COUNT
        )),
    )
    background_guard = max(6, int(round(max(float(fps), 1.0) * 0.20)))
    pre_groups: list[list[int]] = []
    group_spacing = reference_group_size * 3
    for index in range(_TERMINAL_VIDEO_REFERENCE_COUNT):
        group_end = hit_frame - background_guard - index * group_spacing
        group_start = group_end - reference_group_size + 1
        if group_start < 0:
            continue
        pre_groups.append(list(range(group_start, group_end + 1)))
    # Very short clips (or a hit in the first few frames) have no usable
    # pre-hit groups.  Retain the original local window as a compatibility
    # fallback, and use it as a second group when only one pre-hit window fits.
    local_group = list(range(pre_start, pre_end + 1))
    if len(pre_groups) < 2 and len(local_group) >= _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES:
        pre_groups.append(local_group)
    if not pre_groups:
        pre_groups = [local_group]
    pre_frames = sorted({frame for group in pre_groups for frame in group if frame >= 0})
    # Near the end of a rally the last confirmed hit can be only a few frames
    # before the detector's stationary body hint (as in the reference clip).
    # In that case the post-hit reference contains too few independent
    # backgrounds to support the consensus test.  Fall back to a short
    # history immediately before the hit; it is still before the candidate
    # shot and gives the court/advertising background several temporal views.
    if len(pre_frames) < _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES * 2:
        history_end = hit_frame - 2
        history_start = max(
            0,
            history_end - (_TERMINAL_VIDEO_PRE_WINDOW_FRAMES * 3 - 1),
        )
        if history_end >= history_start:
            history_frames = list(range(history_start, history_end + 1))
            if len(history_frames) >= _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES * 2:
                pre_frames = history_frames
    post_frames = list(range(post_start, post_end + 1))
    pre_crops = _video_frame_crops(path, pre_frames, x0=x0, y0=y0, x1=x1, y1=y1)
    post_crops = _video_frame_crops(path, post_frames, x0=x0, y0=y0, x1=x1, y1=y1)
    if len(pre_crops) < 8 or len(post_crops) < _TERMINAL_VIDEO_MIN_VISIBLE_FRAMES:
        return None

    # Build several *independent* temporal background medians.  A player can
    # occupy the search crop for much of one reference interval; comparing to
    # that single median would turn the player's subsequent movement into a
    # persistent white residual.  Requiring agreement across the medians keeps
    # genuine new objects while suppressing court paint and transient bodies.
    pre_frame_numbers = sorted(pre_crops)
    reference_count = min(
        _TERMINAL_VIDEO_REFERENCE_COUNT,
        max(1, len(pre_frame_numbers) // _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES),
    )
    reference_images = []
    chunk_size = max(
        _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES,
        int(math.ceil(len(pre_frame_numbers) / reference_count)),
    )
    for index in range(reference_count):
        start = index * chunk_size
        end = min(len(pre_frame_numbers), start + chunk_size)
        chunk = pre_frame_numbers[start:end]
        if len(chunk) < _TERMINAL_VIDEO_MIN_REFERENCE_FRAMES:
            continue
        reference_images.append(
            np.median(np.stack([pre_crops[frame] for frame in chunk]), axis=0)
            .astype(np.uint8)
        )
    if not reference_images:
        return None
    post_frame_numbers = sorted(post_crops)
    # A full-window median would erase a shuttle that is visible for only the
    # first 8–12 post-occlusion frames (for example when the recording ends or
    # a player walks over it).  Use overlapping short medians as seeds; the
    # per-frame persistence gate below still decides whether a seed is real.
    post_window_size = min(
        12,
        max(_TERMINAL_VIDEO_MIN_VISIBLE_FRAMES, len(post_frame_numbers) // 3),
    )
    post_window_size = min(len(post_frame_numbers), post_window_size)
    post_step = max(1, post_window_size // 2)
    post_window_starts = list(
        range(0, max(1, len(post_frame_numbers) - post_window_size + 1), post_step)
    )
    last_start = max(0, len(post_frame_numbers) - post_window_size)
    if last_start not in post_window_starts:
        post_window_starts.append(last_start)
    post_medians = [
        np.median(
            np.stack([
                post_crops[frame]
                for frame in post_frame_numbers[start:start + post_window_size]
            ]),
            axis=0,
        ).astype(np.uint8)
        for start in post_window_starts
    ]

    def _white_difference(reference, current):
        reference_gray = cv2.cvtColor(reference, cv2.COLOR_BGR2GRAY)
        current_gray = cv2.cvtColor(current, cv2.COLOR_BGR2GRAY)
        difference = current_gray.astype(np.int16) - reference_gray.astype(np.int16)
        hsv = cv2.cvtColor(current, cv2.COLOR_BGR2HSV)
        mask = (
            (difference >= _TERMINAL_VIDEO_DIFF_THRESHOLD)
            & (hsv[:, :, 2] >= _TERMINAL_VIDEO_MIN_VALUE)
            & (hsv[:, :, 1] <= _TERMINAL_VIDEO_MAX_SATURATION)
        ).astype(np.uint8) * 255
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((2, 2), np.uint8))
        return mask

    # A majority vote is deliberately used instead of an AND.  One reference
    # can contain a moving limb or a compression glitch at the landing site;
    # two clean references are enough to establish that a residual is new.
    required_references = max(
        1,
        int(round(_TERMINAL_VIDEO_REFERENCE_AGREEMENT * len(reference_images))),
    )
    if len(reference_images) > 1:
        required_references = max(2, required_references)
    required_references = min(len(reference_images), required_references)

    def _consensus_mask(current):
        masks = [_white_difference(reference, current) > 0 for reference in reference_images]
        support = np.sum(np.stack(masks, axis=0), axis=0)
        mask = (support >= required_references).astype(np.uint8) * 255
        return cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((2, 2), np.uint8))

    def _is_painted_boundary_component(
        px: int,
        py: int,
        pw: int,
        ph: int,
    ) -> bool:
        """Reject a compact residual that lies wholly on the court paint.

        A baseline/side line can be exposed when a player leaves the frame.
        Its short anti-aliased fragments occasionally satisfy the shuttle
        area/shape gates, so geometry—not color alone—must remove them.  A
        real shuttle just outside the line has a visible outward extent and
        therefore is not wholly contained in this narrow band.
        """
        points = [
            (float(px + x0), float(py + y0)),
            (float(px + pw - 1 + x0), float(py + y0)),
            (float(px + x0), float(py + ph - 1 + y0)),
            (float(px + pw - 1 + x0), float(py + ph - 1 + y0)),
        ]
        distances: list[float] = []
        for image_x, image_y in points:
            edge = _boundary_image_point(
                selected_boundary,
                image_x if selected_boundary in {"far_baseline", "near_baseline"} else image_y,
                court_points=court_points,
            )
            if edge is None:
                return False
            distances.append(
                abs(image_y - edge[1])
                if selected_boundary in {"far_baseline", "near_baseline"}
                else abs(image_x - edge[0])
            )
        return bool(distances) and max(distances) <= _TERMINAL_VIDEO_LINE_BAND_PX

    median_mask = np.zeros_like(
        _consensus_mask(post_medians[0]),
        dtype=np.uint8,
    )
    for post_median in post_medians:
        median_mask = cv2.bitwise_or(median_mask, _consensus_mask(post_median))
    count, labels, stats, centroids = cv2.connectedComponentsWithStats(median_mask)
    component_candidates: list[dict[str, Any]] = []
    for index in range(1, int(count)):
        px, py, pw, ph, area = [int(value) for value in stats[index]]
        aspect_ratio = max(pw / max(1.0, float(ph)), ph / max(1.0, float(pw)))
        if not (
            _TERMINAL_VIDEO_MIN_COMPONENT_AREA <= area <= _TERMINAL_VIDEO_MAX_COMPONENT_AREA
            and 2 <= pw <= 14
            and 2 <= ph <= 14
            and area / max(1.0, float(pw * ph)) >= 0.20
            and aspect_ratio <= _TERMINAL_VIDEO_MAX_ASPECT_RATIO
        ):
            continue
        if _is_painted_boundary_component(px, py, pw, ph):
            continue
        cx, cy = [float(value) for value in centroids[index]]
        component_candidates.append({
            "x": cx,
            "y": cy,
            "x0": px,
            "y0": py,
            "x1": px + pw - 1,
            "y1": py + ph - 1,
            "area": area,
        })
    if not component_candidates:
        return None

    # Evaluate each component against individual frames.  A player leg can
    # create a large one-frame difference, but it does not remain a tiny blob
    # at one image coordinate for eight frames.
    best = None
    for component in component_candidates:
        centers: list[tuple[int, float, float, int, int, int, int]] = []
        for frame in sorted(post_crops):
            frame_mask = _consensus_mask(post_crops[frame])
            cc, ll, ss, cs = cv2.connectedComponentsWithStats(frame_mask)
            nearby = []
            for index in range(1, int(cc)):
                px, py, pw, ph, area = [int(value) for value in ss[index]]
                aspect_ratio = max(pw / max(1.0, float(ph)), ph / max(1.0, float(pw)))
                if not (
                    _TERMINAL_VIDEO_MIN_COMPONENT_AREA <= area <= _TERMINAL_VIDEO_MAX_COMPONENT_AREA
                    and 2 <= pw <= 14
                    and 2 <= ph <= 14
                    and area / max(1.0, float(pw * ph)) >= 0.20
                    and aspect_ratio <= _TERMINAL_VIDEO_MAX_ASPECT_RATIO
                ):
                    continue
                if _is_painted_boundary_component(px, py, pw, ph):
                    continue
                cx, cy = [float(value) for value in cs[index]]
                if math.hypot(cx - component["x"], cy - component["y"]) <= 9.0:
                    nearby.append((
                        math.hypot(cx - component["x"], cy - component["y"]),
                        cx, cy, px, py, px + pw - 1, py + ph - 1,
                    ))
            if nearby:
                _, cx, cy, px, py, qx, qy = min(nearby, key=lambda item: item[0])
                centers.append((int(frame), cx, cy, px, py, qx, qy))
        if len(centers) < _TERMINAL_VIDEO_MIN_VISIBLE_FRAMES:
            continue

        # Count the longest temporally contiguous segment, allowing one
        # dropped frame for decoder flicker.  A moving shoe may revisit a
        # coordinate eight times over a long window, but it is not a settled
        # shuttle unless those observations form one uninterrupted run.
        temporal_runs: list[list[tuple[int, float, float, int, int, int, int]]] = []
        for item in centers:
            if not temporal_runs or item[0] - temporal_runs[-1][-1][0] > _TERMINAL_VIDEO_MAX_FRAME_GAP:
                temporal_runs.append([item])
            else:
                temporal_runs[-1].append(item)
        if not temporal_runs:
            continue
        contiguous = max(
            temporal_runs,
            key=lambda run: (len(run), run[-1][0]),
        )
        if len(contiguous) < _TERMINAL_VIDEO_MIN_VISIBLE_FRAMES:
            continue
        centers = contiguous
        center_array = np.asarray([(item[1], item[2]) for item in centers], dtype=float)
        std = float(np.max(np.std(center_array, axis=0)))
        if std > _TERMINAL_VIDEO_MAX_CENTROID_STD_PX:
            continue
        score = len(centers) / max(1, len(post_crops))
        if best is None or (score, len(centers)) > (best[0], best[1]):
            best = (score, len(centers), centers, component)
    if best is None:
        return None
    persistence, visible_count, centers, component = best
    # Convert crop coordinates back to source image coordinates and use the
    # boundary-facing edge of the blob as a conservative contact estimate.
    # Use robust percentiles rather than the absolute union.  A single frame
    # with a player's white sock touching the search neighbourhood must not
    # inflate the contact range from a few decimetres to metres.
    min_x = float(np.percentile([item[3] for item in centers], 15)) + x0
    min_y = float(np.percentile([item[4] for item in centers], 15)) + y0
    max_x = float(np.percentile([item[5] for item in centers], 85)) + x0
    max_y = float(np.percentile([item[6] for item in centers], 85)) + y0
    # A court line can be merged into the lower edge of a white shuttle blob
    # by JPEG/anti-aliasing.  Leave a small pixel guard on the boundary-facing
    # side so the reported contact range does not use the painted line itself.
    edge_guard_px = max(1.0, min(4.0, 0.004 * max(float(court_scale_px), 400.0)))
    center_x = float(np.median([item[1] for item in centers])) + x0
    center_y = float(np.median([item[2] for item in centers])) + y0
    if selected_boundary == "far_baseline":
        boundary_edge = float(max_y - edge_guard_px)
        contact_point = (center_x, boundary_edge)
        bbox_points = [
            (min_x, min_y), (max_x, min_y), (min_x, boundary_edge), (max_x, boundary_edge),
        ]
    elif selected_boundary == "near_baseline":
        boundary_edge = float(min_y + edge_guard_px)
        contact_point = (center_x, boundary_edge)
        bbox_points = [
            (min_x, boundary_edge), (max_x, boundary_edge), (min_x, max_y), (max_x, max_y),
        ]
    elif selected_boundary == "left_sideline":
        boundary_edge = float(max_x - edge_guard_px)
        contact_point = (boundary_edge, center_y)
        bbox_points = [
            (min_x, min_y), (boundary_edge, min_y), (min_x, max_y), (boundary_edge, max_y),
        ]
    else:
        boundary_edge = float(min_x + edge_guard_px)
        contact_point = (boundary_edge, center_y)
        bbox_points = [
            (boundary_edge, min_y), (max_x, min_y), (boundary_edge, max_y), (max_x, max_y),
        ]
    projected_center = _project(matrix, center_x, center_y)
    projected_contact = _project(matrix, *contact_point)
    projected_bbox = [_project(matrix, *point) for point in bbox_points]
    if projected_center is None or projected_contact is None or any(point is None for point in projected_bbox):
        return None
    boundary_center = _boundary_from_point(projected_center, margin_m=0.0)
    if boundary_center is None or boundary_center[0] != selected_boundary:
        return None
    # Keep the plausible ground band tight enough to reject the y≈445 body
    # lock, while allowing a real far/near-baseline miss of roughly a metre.
    outside_values = []
    for point in projected_bbox:
        if selected_boundary == "far_baseline":
            outside_values.append(-float(point[1]))
        elif selected_boundary == "near_baseline":
            outside_values.append(float(point[1]) - COURT_LENGTH_M)
        elif selected_boundary == "left_sideline":
            outside_values.append(-float(point[0]))
        else:
            outside_values.append(float(point[0]) - COURT_WIDTH_M)
    if not outside_values or max(outside_values) <= 0.05 or min(outside_values) < -0.20:
        return None
    # The contact-facing side must itself be outside by a visible amount.
    if selected_boundary == "far_baseline":
        contact_outside = -float(projected_contact[1])
    elif selected_boundary == "near_baseline":
        contact_outside = float(projected_contact[1]) - COURT_LENGTH_M
    elif selected_boundary == "left_sideline":
        contact_outside = -float(projected_contact[0])
    else:
        contact_outside = float(projected_contact[0]) - COURT_WIDTH_M
    if contact_outside <= 0.05:
        return None
    # The visual fallback is still a single-camera projection.  Do not let a
    # small bright sign, shoe, or a homography tail several metres outside
    # the court become a published landing.  Keep this envelope consistent
    # with measured terminal runs (the real reference miss is only about
    # 0.4 m beyond the far baseline).
    if contact_outside > _MAX_CONFIRMED_LANDING_OUTSIDE_M:
        return None
    distance_values_cm = [max(0.0, value) * 100.0 for value in outside_values]
    distance_range = [
        round(max(0.0, min(distance_values_cm)), 1),
        round(max(distance_values_cm), 1),
    ]
    # Preserve the same 20 cm line ambiguity used by measured landings.  The
    # boundary-facing blob edge is intentionally conservative and can sit
    # back inside the line even when most of the recovered shuttle is clearly
    # outside.  Use the midpoint of the projected range for the call, while
    # retaining the full range for the UI; this keeps a clear 30–40 cm miss as
    # OUT but leaves a genuinely line-adjacent object as REVIEW.
    representative_outside = sum(distance_range) / 200.0
    if distance_range[0] < LINE_AMBIGUITY_M * 100.0:
        decision = "review"
    else:
        decision = _decision(-float(representative_outside))
    confidence = int(round(58.0 + 22.0 * min(1.0, persistence) + 8.0 * min(1.0, visible_count / 20.0)))
    # Video recovery establishes a useful visual event, but it is not a
    # calibrated multi-camera Hawk-Eye measurement.  Keep the displayed
    # quality below the "high" tier even with long persistence.
    confidence = max(66, min(80, confidence))
    first_visible_frame = min(int(item[0]) for item in centers)
    return {
        "frame": int(first_visible_frame),
        "seconds": round(first_visible_frame / max(float(fps), 1.0), 2),
        "timecode": _timecode(first_visible_frame, fps),
        "landing": {
            "x_m": round(float(projected_center[0]), 3),
            "y_m": round(float(projected_center[1]), 3),
        },
        "contact_landing": {
            "x_m": round(float(projected_contact[0]), 3),
            "y_m": round(float(projected_contact[1]), 3),
        },
        "line_distance_cm": round(sum(distance_range) / 2.0, 1),
        "line_distance_range_cm": distance_range,
        "boundary": selected_boundary,
        "decision": decision,
        "method": "visible_terminal_rest_after_occlusion",
        "confidence": confidence,
        "confidence_level": "high" if confidence >= 82 else "medium",
        "evidence_frames": int(visible_count),
        "persistence": round(float(persistence), 3),
        "rest_bbox": {
            "x0": int(min_x), "y0": int(min_y),
            "x1": int(max_x), "y1": int(max_y),
        },
    }


def _candidate_for_rally(
    rally_id: int,
    rows: Sequence[Mapping[str, object]],
    *,
    fps: float,
    matrix,
    court_points: Sequence[object],
    force_review: bool,
    court_scale_px: float = 800.0,
    video_path: Path | str | None = None,
) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    ordered = sorted(rows, key=lambda row: _integer(row.get("Frame"), -1))
    raw_hits = [
        row for row in ordered
        if _integer(row.get("Hit"), 0) > 0 and _integer(row.get("Frame"), -1) >= 0
    ]
    hits = [row for row in raw_hits if _is_confirmed_hit(row)]
    diagnostic: dict[str, Any] = {
        "reason_codes": [],
        "ignored_unconfirmed_hits": len(raw_hits) - len(hits),
        "rejected_newer_runs": 0,
    }
    if not hits:
        diagnostic["reason_codes"].append("no_confirmed_hit")
        return None, diagnostic
    final_hit = hits[-1]
    hit_frame = _integer(final_hit.get("Frame"), -1)
    # ``ShotEndFrame`` is filled when the next contact has been associated
    # with this shot.  In that case this is an in-rally flight, never a rally
    # terminal landing, even if a later tracker branch happens to settle.
    shot_end_frame = _integer(final_hit.get("ShotEndFrame"), -1)
    # ``ShotEndFrame`` is a soft association in legacy sidecars: it may point
    # at a HIT? generated by a body/ball-racket lock.  A missing endpoint row
    # or a confirmed endpoint remains a hard continuation; an uncertain row
    # must pass the two-sided flight gate below.
    soft_context_end = -1
    if shot_end_frame > hit_frame:
        endpoint_row = next(
            (
                row for row in ordered
                if _integer(row.get("Frame"), -1) == shot_end_frame
            ),
            None,
        )
        endpoint_is_valid = bool(
            endpoint_row is None
            or _is_confirmed_hit(endpoint_row)
            or _uncertain_hit_has_two_sided_flight(
                endpoint_row,
                ordered,
                court_scale_px=court_scale_px,
            )
        )
        if endpoint_is_valid:
            diagnostic["reason_codes"].append("shot_continues_to_next_contact")
            return None, diagnostic
        # Keep the association as an upper bound for detector context, but do
        # not throw away the terminal flight or a video-rest object after it.
        soft_context_end = shot_end_frame
    # A high-confidence HIT? with an observed shuttle is evidence that the
    # rally may have continued, even when the local sidecar does not contain
    # enough points to prove a two-sided flight.  In a sidecar-only review we
    # must therefore decline the preceding endpoint.  When the source video
    # is available, defer the decision to the independent visual-rest
    # recovery below; this is what lets an occluded final OUT remain
    # recoverable without accepting the body-lock point as a landing.
    strong_uncertain_requires_video = False
    for row in ordered:
        row_frame = _integer(row.get("Frame"), -1)
        if row_frame <= hit_frame or not _is_strong_unconfirmed_hit(row):
            continue
        if _uncertain_hit_has_two_sided_flight(
            row,
            ordered,
            court_scale_px=court_scale_px,
        ):
            continue
        if not video_path or force_review:
            diagnostic["reason_codes"].append("later_hit_unconfirmed")
            return None, diagnostic
        strong_uncertain_requires_video = True
    # Legacy sidecars may omit ShotEndFrame.  Preserve their compatibility,
    # but do not continue past a strong uncertain contact (pose + observed
    # ball evidence) as though it were a landing.
    if any(
        _integer(row.get("Frame"), -1) > hit_frame
        and _uncertain_hit_has_two_sided_flight(
            row,
            ordered,
            court_scale_px=court_scale_px,
        )
        for row in ordered
    ):
        diagnostic["reason_codes"].append("later_hit_unconfirmed")
        return None, diagnostic
    hitter = str(final_hit.get("HitHitter", "")).strip().lower()
    if hitter not in {"near", "far"}:
        hitter = "unknown"
    hitter_source = str(final_hit.get("HitHitterSource", "")).strip().lower()
    review_only_hitter = hitter_source in _REVIEW_ONLY_HITTER_SOURCES
    # Do not let an alternation repair reject a terminal run in the apparent
    # "wrong" half, boost its target score, or yield a hard IN/OUT decision.
    # Preserve it as a normal review candidate with an unconfirmed hitter.
    effective_hitter = "unknown" if review_only_hitter else hitter
    observations = [
        item for row in ordered
        if (
            _integer(row.get("Frame"), -1) > hit_frame
            and (
                soft_context_end < 0
                or _integer(row.get("Frame"), -1) <= soft_context_end
            )
        )
        for item in [_observation(row)]
        if item is not None
    ]
    if not observations and not strong_uncertain_requires_video:
        diagnostic["reason_codes"].append("no_post_hit_observation")
        return None, diagnostic
    # Sidecars are frame-indexed.  Permit one missing frame for detector
    # flicker, but do not bridge a longer disappearance into a fake landing.
    # A lone late detector response can occur after a valid final flight; it
    # must not erase that prior coherent terminal evidence.
    runs = _observation_runs(observations, max_gap_frames=2)
    coherent_runs = [run for run in runs if len(run) >= 3]
    if not coherent_runs and not strong_uncertain_requires_video:
        diagnostic["reason_codes"].append("discontinuous_terminal_track")
        return None, diagnostic

    # A strong uncertain contact can only be resolved by the source-video
    # fallback.  Do not let a prior/stationary sidecar branch short-circuit
    # that independent check.
    if strong_uncertain_requires_video:
        coherent_runs = []

    # Inspect coherent branches newest-first.  A branch after a real detector
    # gap cannot prove a new landing: it is commonly a player/net lock.  The
    # gate is based on the raw frame gap, not projected distance, so a false
    # branch that happens to fall inside the homography cannot replace an
    # earlier coherent event.
    for run_index in range(len(coherent_runs) - 1, -1, -1):
        tail = coherent_runs[run_index]
        late_discontinuous_branch = False
        if run_index > 0:
            previous_frame = int(coherent_runs[run_index - 1][-1]["frame"])
            start_frame = int(tail[0]["frame"])
            late_discontinuous_branch = start_frame - previous_frame > 2
        reason_code = ""
        terminal_frame = int(tail[-1]["frame"])
        flight_frames = terminal_frame - hit_frame
        if flight_frames < max(3, int(round(max(fps, 1.0) * 0.18))):
            reason_code = "flight_too_short"
        if reason_code:
            diagnostic["reason_codes"].append(reason_code)
            diagnostic["rejected_newer_runs"] += 1
            continue

        if late_discontinuous_branch:
            diagnostic["reason_codes"].append("discontinuous_terminal_track")
            diagnostic["rejected_newer_runs"] += 1
            continue
        evidence = _landing_event_evidence(
            tail,
            fps=fps,
            court_scale_px=court_scale_px,
        )
        if evidence is None:
            diagnostic["reason_codes"].append("no_landing_evidence")
            diagnostic["rejected_newer_runs"] += 1
            continue
        # Only the settled, real observations are projected.  In particular,
        # never average airborne points or an interpolated/off-screen bridge
        # into a floor coordinate.
        projected_point = _project(matrix, evidence["x"], evidence["y"])
        if projected_point is None:
            diagnostic["reason_codes"].append("projection_failed")
            diagnostic["rejected_newer_runs"] += 1
            continue
        x_m, y_m = projected_point
        method = "visible_rest"
        if not (
            -_MAX_ENDPOINT_OUTSIDE_M <= x_m <= COURT_WIDTH_M + _MAX_ENDPOINT_OUTSIDE_M
            and -_MAX_ENDPOINT_OUTSIDE_M <= y_m <= COURT_LENGTH_M + _MAX_ENDPOINT_OUTSIDE_M
        ):
            diagnostic["reason_codes"].append("landing_out_of_bounds")
            diagnostic["rejected_newer_runs"] += 1
            continue
        signed_distance = _signed_line_distance(x_m, y_m)
        if signed_distance < -_MAX_CONFIRMED_LANDING_OUTSIDE_M:
            diagnostic["reason_codes"].append("landing_out_of_bounds")
            diagnostic["rejected_newer_runs"] += 1
            continue
        target_ok = _expected_target_ok(effective_hitter, y_m)
        if target_ok is False:
            diagnostic["reason_codes"].append("wrong_target_half")
            diagnostic["rejected_newer_runs"] += 1
            continue
        average_confidence = sum(float(item["confidence"]) for item in tail) / len(tail)
        run_signal = min(1.0, len(tail) / 5.0)
        flight_signal = min(1.0, flight_frames / max(1.0, fps * 0.70))
        target_signal = 1.0 if target_ok is True else 0.68
        confidence = int(round(100.0 * (
            0.38 * run_signal
            + 0.25 * average_confidence
            + 0.22 * flight_signal
            + 0.15 * target_signal
        )))
        fallback_review = diagnostic["rejected_newer_runs"] > 0
        if (
            force_review
            or effective_hitter == "unknown"
            or fallback_review
        ):
            confidence = min(confidence, 79)
        if confidence < 66:
            diagnostic["reason_codes"].append("low_confidence")
            diagnostic["rejected_newer_runs"] += 1
            continue
        decision = (
            _decision(signed_distance)
            if (
                effective_hitter != "unknown"
                and not force_review
                and not fallback_review
            )
            else "review"
        )
        diagnostic["selected_terminal_frame"] = terminal_frame
        return {
            "rally_id": int(rally_id),
            "frame": terminal_frame,
            "seconds": round(terminal_frame / max(float(fps), 1.0), 2),
            "timecode": _timecode(terminal_frame, fps),
            "hit_frame": hit_frame,
            "hitter": effective_hitter,
            "hitter_source": hitter_source,
            "hitter_review_only": review_only_hitter,
            "landing": {"x_m": round(x_m, 3), "y_m": round(y_m, 3)},
            "decision": decision,
            "method": method,
            "line_distance_cm": round(abs(signed_distance) * 100.0, 1),
            "confidence": max(0, min(100, confidence)),
            "confidence_level": "high" if confidence >= 82 else "medium",
            "evidence_frames": len(tail),
        }, diagnostic

    # TrackNet often suppresses a shuttle after it comes to rest, while a
    # classical/pose branch may lock onto a nearby player.  If the source
    # video is available, recover a small persistent white object near the
    # terminal boundary.  The soft ShotEndFrame is used only to stop reading
    # the post-contact body branch; the video search itself continues beyond
    # it so a recovered shuttle is not lost.
    if video_path and not force_review:
        context_end = soft_context_end
        if context_end < 0:
            context_end = max(
                (_integer(row.get("Frame"), -1) for row in ordered),
                default=hit_frame,
            )
        recovered = _recover_terminal_rest_from_video(
            video_path,
            ordered,
            hit_frame=hit_frame,
            context_end_frame=context_end,
            fps=fps,
            matrix=matrix,
            court_points=court_points,
            court_scale_px=court_scale_px,
        )
        if recovered is not None:
            diagnostic["terminal_rest_recovered"] = True
            diagnostic["selected_terminal_frame"] = _integer(
                recovered.get("frame"), -1
            )
            candidate = {
                "rally_id": int(rally_id),
                "frame": int(recovered["frame"]),
                "seconds": float(recovered["seconds"]),
                "timecode": str(recovered["timecode"]),
                "hit_frame": hit_frame,
                "hitter": effective_hitter,
                "hitter_source": hitter_source,
                "hitter_review_only": review_only_hitter,
                "landing": recovered.get("landing"),
                "contact_landing": recovered.get("contact_landing"),
                "decision": str(recovered.get("decision", "review")),
                "call_hint": "out" if str(recovered.get("decision")) == "out" else "review",
                "boundary": str(recovered.get("boundary", "")),
                "method": str(recovered.get("method", "visible_terminal_rest_after_occlusion")),
                "line_distance_cm": float(recovered.get("line_distance_cm", 0.0)),
                "line_distance_range_cm": recovered.get("line_distance_range_cm"),
                "confidence": int(recovered.get("confidence", 0)),
                "confidence_level": str(recovered.get("confidence_level", "medium")),
                "evidence_frames": int(recovered.get("evidence_frames", 0)),
                "persistence": float(recovered.get("persistence", 0.0)),
            }
            return candidate, diagnostic
    if strong_uncertain_requires_video:
        diagnostic["reason_codes"].append("later_hit_unconfirmed")
    return None, diagnostic


def _aggregate_diagnostics(
    entries: Sequence[Mapping[str, object]],
) -> dict[str, Any]:
    counts: dict[str, int] = {}
    ignored_unconfirmed_hits = 0
    fallback_candidate_count = 0
    for entry in entries:
        raw_codes = entry.get("reason_codes", [])
        if isinstance(raw_codes, (list, tuple)):
            for raw_code in raw_codes:
                code = str(raw_code)
                if code in _REJECTION_CODES:
                    counts[code] = counts.get(code, 0) + 1
        ignored_unconfirmed_hits += max(
            0, _integer(entry.get("ignored_unconfirmed_hits"), 0)
        )
        if (
            _integer(entry.get("selected_terminal_frame"), -1) >= 0
            and _integer(entry.get("rejected_newer_runs"), 0) > 0
        ):
            fallback_candidate_count += 1

    priority = {code: index for index, code in enumerate(_REJECTION_CODES)}
    reason_counts = [
        {"code": code, "count": count}
        for code, count in sorted(
            counts.items(),
            key=lambda item: (-item[1], priority.get(item[0], len(priority))),
        )
    ]
    result: dict[str, Any] = {"reason_counts": reason_counts}
    if ignored_unconfirmed_hits:
        result["ignored_unconfirmed_hits"] = ignored_unconfirmed_hits
    if fallback_candidate_count:
        result["fallback_candidate_count"] = fallback_candidate_count
    return result


def build_hawkeye_report(
    rows: Iterable[Mapping[str, object]],
    *,
    fps: float,
    court_points: Sequence[object],
    force_review: bool = False,
    video_path: Path | str | None = None,
) -> dict[str, Any]:
    """Produce a path-free report from the tracking sidecar rows.

    Only measured terminal runs after the final confirmed hit in each rally
    are eligible.  This intentionally declines ordinary in-rally flights:
    they end at a racket contact, not a floor landing.
    """
    matrix = _court_homography(court_points)
    if matrix is None:
        return _empty_report(
            "unavailable",
            "球场四点标定无效，未生成鹰眼辅助复核。",
            reason_code="invalid_calibration",
        )
    court_scale_px = _court_pixel_scale(court_points)
    groups: dict[int, list[Mapping[str, object]]] = {}
    for row in rows:
        if not isinstance(row, Mapping):
            continue
        rally_id = _integer(row.get("RallyID"), 0)
        if rally_id > 0:
            groups.setdefault(rally_id, []).append(row)
    candidates = []
    rally_diagnostics: list[dict[str, Any]] = []
    for rally_id in sorted(groups):
        candidate, diagnostic = _candidate_for_rally(
            rally_id,
            groups[rally_id],
            fps=max(float(fps), 1.0),
            matrix=matrix,
            court_points=court_points,
            force_review=bool(force_review),
            court_scale_px=court_scale_px,
            video_path=video_path,
        )
        rally_diagnostics.append(diagnostic)
        if candidate is not None:
            candidates.append(candidate)
    candidates = candidates[:_MAX_CANDIDATES]
    if not groups:
        rally_diagnostics.append({"reason_codes": ["no_rallies"]})
    diagnostics = _aggregate_diagnostics(rally_diagnostics)
    if not candidates:
        reason_counts = diagnostics.get("reason_counts", [])
        primary_code = (
            str(reason_counts[0].get("code", ""))
            if isinstance(reason_counts, list)
            and reason_counts
            and isinstance(reason_counts[0], Mapping)
            else ""
        )
        primary_notice = _REJECTION_NOTICES.get(primary_code)
        notice = (
            f"未生成落点：{primary_notice}。常规击球与回合分析不受影响。"
            if primary_notice
            else "没有足够连续的终局轨迹证据，未生成落点候选；这不会影响常规击球与回合分析。"
        )
        report = _empty_report(
            "insufficient_evidence",
            notice,
        )
        report["summary"]["reviewed_rallies"] = len(groups)
        report["diagnostics"] = diagnostics
        return report
    summary = {
        "reviewed_rallies": len(groups),
        "candidate_count": len(candidates),
        "in_count": sum(item["decision"] == "in" for item in candidates),
        "out_count": sum(item["decision"] == "out" for item in candidates),
        "review_count": sum(item["decision"] == "review" for item in candidates),
    }
    notice = (
        f"单机位二维轨迹复核：生成 {len(candidates)} 个回合终局落点候选。"
        f"距边线 {int(round(LINE_AMBIGUITY_M * 100))} cm 内统一标为“待复核”。"
        "实测落地且击球方已确认的轨迹给出 IN/OUT；遮挡后恢复的边界目标可直接标记 OUT，"
        "其余仅作视频复核。"
    )
    review_only_hitter_count = sum(
        bool(item.get("hitter_review_only", False)) for item in candidates
    )
    if review_only_hitter_count:
        notice += (
            f" 其中 {review_only_hitter_count} 个候选的击球方仅由回合交替推断，"
            "统一降级为待复核。"
        )
    if force_review:
        notice += " 当前启用了跨硬切继续，所有候选均降级为待复核。"
    ignored_unconfirmed_hits = _integer(
        diagnostics.get("ignored_unconfirmed_hits"), 0
    )
    if ignored_unconfirmed_hits:
        notice += f" 已忽略 {ignored_unconfirmed_hits} 个未确认击球事件。"
    fallback_candidate_count = _integer(
        diagnostics.get("fallback_candidate_count"), 0
    )
    if fallback_candidate_count:
        notice += (
            f" {fallback_candidate_count} 个候选已排除异常末端轨迹，"
            "回退到最近可信终局轨迹。"
        )
    return {
        "version": 1,
        "status": "ready",
        "notice": notice,
        "court": {
            "width_m": COURT_WIDTH_M,
            "length_m": COURT_LENGTH_M,
            "line_margin_cm": int(round(LINE_AMBIGUITY_M * 100)),
        },
        "summary": summary,
        "diagnostics": diagnostics,
        "candidates": candidates,
    }


def run_hawkeye_review(
    sidecar_path: Path | str,
    *,
    fps: float,
    court_points: Sequence[object],
    force_review: bool = False,
    video_path: Path | str | None = None,
) -> dict[str, Any]:
    """Read the sidecar defensively; a review failure never fails the job."""
    path = Path(sidecar_path)
    if not path.is_file():
        return _empty_report(
            "unavailable",
            "轨迹数据不可用，未生成鹰眼辅助复核。",
            reason_code="source_unavailable",
        )
    try:
        with path.open("r", encoding="utf-8", newline="") as stream:
            rows = list(csv.DictReader(stream))
        return build_hawkeye_report(
            rows,
            fps=fps,
            court_points=court_points,
            force_review=force_review,
            video_path=video_path,
        )
    except Exception:
        return _empty_report(
            "unavailable",
            "轨迹复核读取失败，未生成鹰眼辅助结果。",
            reason_code="read_failed",
        )


__all__ = [
    "COURT_LENGTH_M",
    "COURT_WIDTH_M",
    "LINE_AMBIGUITY_M",
    "build_hawkeye_report",
    "run_hawkeye_review",
]
